"""remove password_hash from users table

Revision ID: 9a9dbc7292b8
Revises: 9cc4f012508b
Create Date: 2025-09-19 05:21:04.408726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9dbc7292b8'
down_revision = '9cc4f012508b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_auth0_user_id'))
        batch_op.drop_column('auth0_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_auth0_user_id'), ['auth0_user_id'], unique=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_auth0_user_id'))
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_permissions_auth0_user_id'), ['auth0_user_id'], unique=True)

    # ### end Alembic commands ###
