"""add auth0_user_id to users table

Revision ID: 9cc4f012508b
Revises: 0db1eab8c78a
Create Date: 2025-09-19 05:13:40.913895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc4f012508b'
down_revision = '0db1eab8c78a'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_user_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth0_user_id')


    # ### end Alembic commands ###
